package com.acitivi.po;

import java.util.Date;

public class AdminUserAuthPO {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminuserauth.Id
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminuserauth.User_Id
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	private Integer user_Id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminuserauth.Org_Id
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	private Integer org_Id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminuserauth.UserRole
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	private String userRole;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminuserauth.CreateTime
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminuserauth.CreateUser_Id
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	private Integer createUser_Id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminuserauth.LastUpdateTime
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	private Date lastUpdateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminuserauth.LastUpdateUser_Id
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	private Integer lastUpdateUser_Id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminuserauth.OrgType
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	private Integer orgType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminuserauth.State
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	private Byte state;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminuserauth.Id
	 * @return  the value of adminuserauth.Id
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminuserauth.Id
	 * @param id  the value for adminuserauth.Id
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminuserauth.User_Id
	 * @return  the value of adminuserauth.User_Id
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	public Integer getUser_Id() {
		return user_Id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminuserauth.User_Id
	 * @param user_Id  the value for adminuserauth.User_Id
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	public void setUser_Id(Integer user_Id) {
		this.user_Id = user_Id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminuserauth.Org_Id
	 * @return  the value of adminuserauth.Org_Id
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	public Integer getOrg_Id() {
		return org_Id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminuserauth.Org_Id
	 * @param org_Id  the value for adminuserauth.Org_Id
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	public void setOrg_Id(Integer org_Id) {
		this.org_Id = org_Id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminuserauth.UserRole
	 * @return  the value of adminuserauth.UserRole
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	public String getUserRole() {
		return userRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminuserauth.UserRole
	 * @param userRole  the value for adminuserauth.UserRole
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	public void setUserRole(String userRole) {
		this.userRole = userRole == null ? null : userRole.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminuserauth.CreateTime
	 * @return  the value of adminuserauth.CreateTime
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminuserauth.CreateTime
	 * @param createTime  the value for adminuserauth.CreateTime
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminuserauth.CreateUser_Id
	 * @return  the value of adminuserauth.CreateUser_Id
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	public Integer getCreateUser_Id() {
		return createUser_Id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminuserauth.CreateUser_Id
	 * @param createUser_Id  the value for adminuserauth.CreateUser_Id
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	public void setCreateUser_Id(Integer createUser_Id) {
		this.createUser_Id = createUser_Id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminuserauth.LastUpdateTime
	 * @return  the value of adminuserauth.LastUpdateTime
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	public Date getLastUpdateTime() {
		return lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminuserauth.LastUpdateTime
	 * @param lastUpdateTime  the value for adminuserauth.LastUpdateTime
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminuserauth.LastUpdateUser_Id
	 * @return  the value of adminuserauth.LastUpdateUser_Id
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	public Integer getLastUpdateUser_Id() {
		return lastUpdateUser_Id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminuserauth.LastUpdateUser_Id
	 * @param lastUpdateUser_Id  the value for adminuserauth.LastUpdateUser_Id
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	public void setLastUpdateUser_Id(Integer lastUpdateUser_Id) {
		this.lastUpdateUser_Id = lastUpdateUser_Id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminuserauth.OrgType
	 * @return  the value of adminuserauth.OrgType
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	public Integer getOrgType() {
		return orgType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminuserauth.OrgType
	 * @param orgType  the value for adminuserauth.OrgType
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	public void setOrgType(Integer orgType) {
		this.orgType = orgType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminuserauth.State
	 * @return  the value of adminuserauth.State
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	public Byte getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminuserauth.State
	 * @param state  the value for adminuserauth.State
	 * @mbggenerated  Tue Oct 16 19:37:27 CST 2018
	 */
	public void setState(Byte state) {
		this.state = state;
	}
}