package com.acitivi.dao;

import com.acitivi.po.AdminUserPO;

public interface AdminUserPOMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * adminuser
	 * @mbggenerated Wed Nov 28 14:28:20 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * adminuser
	 * @mbggenerated Wed Nov 28 14:28:20 CST 2018
	 */
	int insert(AdminUserPO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * adminuser
	 * @mbggenerated Wed Nov 28 14:28:20 CST 2018
	 */
	int insertSelective(AdminUserPO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * adminuser
	 * @mbggenerated Wed Nov 28 14:28:20 CST 2018
	 */
	AdminUserPO selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * adminuser
	 * @mbggenerated Wed Nov 28 14:28:20 CST 2018
	 */
	int updateByPrimaryKeySelective(AdminUserPO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * adminuser
	 * @mbggenerated Wed Nov 28 14:28:20 CST 2018
	 */
	int updateByPrimaryKey(AdminUserPO record);

}
